### ISSUE TITLE
parse fragments

### ISSUE THREAD

**Issue by wanderer** [drom/wast-parser#12]
It would be nice to be able to parse wasm text fragments such as  
`(func 0(param i32))`. Currently everything needs to be wrapped in `module` and `func`

**Comment by drom** [comment]
@wanderer do we need to be able starting anywhere?

**Comment by wanderer** [comment]
@drom yeah i think so...  if we had "anywhere" I should be able to replace things like [this](https://github.com/wanderer/wasm-metering/blob/master/index.js#L30-L48) with something like this

``` javascript
const wasm = `(import "ethereum" "gasAdd" (param i32))`
const json = parse(wasm)
```

which is a bit more readable

**Comment by drom** [comment]
@wanderer please try it.
