### ISSUE TITLE
nested array parser

### ISSUE THREAD

**Issue by drom** [drom/wast-parser#14]
`(a (b (c d e)))` -- S-expression
`["a", ["b", ["c", "d", "e"]]]` -- H-expression ?
Whould be easy to construct expressions inside JavaScript

**Comment by wanderer** [comment]
i think thats what this does https://www.npmjs.com/package/s-expression

**Comment by drom** [comment]
@wanderer the idea here is provide easy way of WAST construction with JS Arrays:

``` js
var hparser = require('wast-parser').hparser;
var node = hparser(['i32.add', ['i32.const', 2], ['i32.const', 3]]);
// node -->
// { kind: 'add',
//   type: 'i32,
//   left: { kind: 'const' ... },
//   right: { kind: 'const' ... }
// }
```

**Comment by wanderer** [comment]
maybe you could build a multi phase parser. `s-expression -> H-expression -> json AST`  
Why are they called  H-expression ?

**Comment by drom** [comment]
H-expression -- is just temporal name for something that I don't know how to call.
S = ( + )
H = [ + ]
H = (resembles pair of square brackets)?
Do you have better name?

S-expression in WASM is very specific textual representation.
H-expression is JS Array Object. Partially parsed S-expression, something easy to construct in JS, better then text string. Resembles S-expression literally.

**Comment by drom** [comment]
We have #3 for multi phase parser. `s-expression -> H-expression -> json AST`

**Comment by wanderer** [comment]
> Do you have better name?

we just call them nested arrays

**Comment by drom** [comment]
Become less important since WASM moving towards stack machine full steam ahead.
