### ISSUE TITLE
identifiers starting with parentheses are not parsed correctly

### ISSUE THREAD

**Issue by axic** [drom/wast-parser#17]
This is an output from `sexpr-wasm-prototype/wasm-wast`, so I'm not entirely sure it is within the bounds of the spec, but `sexpr-wasm` can parse it nonetheless.

```
  (type (;0;) (func (param i32 i32)))
  (type (;1;) (func (param i32)))
  (type (;2;) (func (param i64 i64 i64 i64 i32) (result i32)))
  (type (;3;) (func (param i32) (result i32)))
  (type (;4;) (func (param i32 i32) (result i32)))
  (type (;5;) (func (param i64 i64 i64 i64) (result i32)))
  (type (;6;) (func))
  (import (;0;) "debug" "print" (type 1))
  (func (;0;) (type 2) (param i64 i64 i64 i64 i32) (result i32)
```

The identifiers (`(;0;)`, ...) are not parsed and missing from the JSON:

```
{"kind":"type","expr":{"kind":"func","params":[{"kind":"param","items":[{"kind":"item","type":"i32"},{"kind":"item","type":"i32"}]}],"result":null,"local":[],"body":[]},"id":null}
```

**Comment by drom** [comment]
@axic `(;0;)` is the comment. Parser not including comments into JSON AST. It is probably done to simplify readability of the code.

**Comment by drom** [comment]
@axic please reopen if further action is needed.

**Comment by axic** [comment]
I'm not entirely familiar with every bit of the AST spec, but `wasm-wast` (binary to wast converter) produces that output and it is able to convert it back to binary.

Are you sure it is invalid according to the AST spec?

**Comment by axic** [comment]
@binji could you comment on this?

**Comment by binji** [comment]
@axic Yes, @drom is correct. This is just a comment to help readability. It's valid to include but it's not necessary to output.

**Comment by axic** [comment]
@binji thank you. I have just realised they were referred to by their indexes later on.

I agree it doesn't belong to parser. I'll open an issue on codegen, because it seems like a useful optional feature there.
