### ISSUE TITLE
binaryan -> SyntaxError

### ISSUE THREAD

**Issue by pannous** [drom/wast-parser#22]
Is wast-parser not compatible with binaryan wast?

```
  (module
    (export "add" $add)
    (func $add (param $x f64) (param $y f64) (result f64)
      (f64.add
        (get_local $x)
        (get_local $y)
      )
    )
  )
```
SyntaxError: Expected "(", "memory", comment, end of line or whitespace but "$" found.

**Comment by drom** [comment]
@pannous yep. looking into it.

**Comment by drom** [comment]
@pannous please try. It should be fixed in v0.30.0

**Comment by pannous** [comment]
wow, fabulous, that was quick!

It's not yet available via `npm update -g  wast-parser` though, right?

**Comment by drom** [comment]
@pannous it is: https://www.npmjs.com/search?q=wast-parser
