### ISSUE TITLE
Difference to binaryan

### ISSUE THREAD

**Issue by pannous** [drom/wast-parser#29]
What is the motivation for creating a 'second binaryan.js',  or what are the differences?
Isn't WAST already an AST?

**Comment by pannous** [comment]
OK, WAST is an AST in text format, got it ;)

still, why not use
```
var module = new Binaryen.Module();
var parser = new Binaryen.SExpressionParser(input);
parser.get_root().dump();
var s_module = parser.get_root().getChild(0);
```

**Comment by drom** [comment]
@pannous I guess:
 * There where no such thing as `binaryan.js` when I started (Oct 14, 2015)
 * I need simple NPM package that just takes string and produces JSON (object)

**Comment by pannous** [comment]
Oh I meant binaryen (with 'e') 

https://github.com/WebAssembly/binaryen 

https://github.com/WebAssembly/binaryen/blob/master/bin/binaryen.js

**Comment by pannous** [comment]
True, `npm install --save -g binaryen` doesnt work unlike yours
