### ISSUE TITLE
binary -> json AST

### ISSUE THREAD

**Issue by wanderer** [drom/wast-parser#8]
Since the binary format has now been specified it would  be nice to be able to go directly from binary to json AST. Would that make sense in the repo?

**Comment by drom** [comment]
I think this should be separate repo. Because binary decoder code will be completely different.
I have separate repo for `json -> bytecode` here: https://github.com/drom/wast-asm
and I just created create new repo for `bytecode -> json` here: https://github.com/drom/wast-diz

**Comment by wanderer** [comment]
cool!
